name:                Hasi
version:             0.1.0.0
github:              "scsmithr/Hasi"
license:             BSD3
author:              "Sean Smith"
maintainer:          "scsmithr@gmail.com"
copyright:           "2021 Sean Smith"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hasi#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.12.0
- mtl >= 2.2.2
- hspec >= 2.7.8
- binary >= 0.8.8

library:
  source-dirs: src

executables:
  Hasi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hasi

tests:
  Hasi2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hasi
